"""Dual Piper EVA Sim: ZMQ teleoperation data collection in joint space."""

_base_ = ['../01_deploy/dual_agilex_piper/eva_sim_openpi_qpos_zmq.py']

# The ZMQ execution node publishes each source-aligned observation together with
# its teleoperation qpos action, so no per-topic collection mapping is needed.
collection = dict(
    storage=dict(
        log_dir='work_dirs/collection/dual_agilex_piper_eva_sim_openpi_qpos_zmq',
        fps=10,
        save_queue_max=15,
    ),
    schema=dict(
        robot_type='agilex_piper',
        min_episode_frames=10,
        arms=dict(
            left_arm='left',
            right_arm='right',
        ),
        cameras=dict(
            cam_high='observation.images.cam_high',
            cam_left_wrist='observation.images.cam_left_wrist',
            cam_right_wrist='observation.images.cam_right_wrist',
        ),
        columns=dict(
            qpos='observations.state.qpos',
            action_qpos='action.qpos',
        ),
    ),
    tasks = [ "s00 pick up the orange block and place it on the green plate.",
      "s00 pick up the green block and place it on the green plate.",
      "s00 pick up the light blue fork and place it on the green plate.",
      "s00 pick up the yellow cup and place it on the green plate.",
      "s00 pick up the mango and place it on the green plate.",
      "s00 pick up the gray cup and place it on the green plate.",
      "s01 pick up the banana and place it on the green plate.",
      "s01 pick up the gray cup and place it on the green plate.",
      "s01 pick up the yellow spoon and place it on the green plate.",
      "s01 pick up the orange block and place it on the green plate.",
      "s01 pick up the yellow cup and place it on the green plate.",
      "s01 pick up the star fruit and place it on the green plate.",
      "s02 pick up the light blue fork and place it on the green plate.",
      "s02 pick up the banana and place it on the green plate.",
      "s02 pick up the green block and place it on the green plate.",
      "s02 pick up the gray cup and place it on the green plate.",
      "s02 pick up the green knife and place it on the green plate.",
      "s02 pick up the yellow spoon and place it on the green plate.",
      "s03 pick up the star fruit and place it on the green plate.",
      "s03 pick up the orange block and place it on the green plate.",
      "s03 pick up the yellow cup and place it on the green plate.",
      "s03 pick up the gray cup and place it on the green plate.",
      "s03 pick up the mango and place it on the green plate.",
      "s03 pick up the green block and place it on the green plate.",
      "s04 pick up the yellow cup and place it on the green plate.",
      "s04 pick up the star fruit and place it on the green plate.",
      "s04 pick up the green knife and place it on the green plate.",
      "s04 pick up the green block and place it on the green plate.",
      "s04 pick up the gray cup and place it on the green plate.",
      "s04 pick up the light blue fork and place it on the green plate.",
      "s05 pick up the orange block and place it on the green plate.",
      "s05 pick up the gray cup and place it on the green plate.",
      "s05 pick up the yellow cup and place it on the green plate.",
      "s05 pick up the green block and place it on the green plate.",
      "s05 pick up the yellow spoon and place it on the green plate.",
      "s05 pick up the banana and place it on the green plate.",
      "s06 pick up the yellow cup and place it on the green plate.",
      "s06 pick up the green knife and place it on the green plate.",
      "s06 pick up the orange block and place it on the green plate.",
      "s06 pick up the mango and place it on the green plate.",
      "s06 pick up the star fruit and place it on the green plate.",
      "s06 pick up the gray cup and place it on the green plate.",
      "s07 pick up the yellow spoon and place it on the green plate.",
      "s07 pick up the mango and place it on the green plate.",
      "s07 pick up the light blue fork and place it on the green plate.",
      "s07 pick up the green knife and place it on the green plate.",
      "s07 pick up the green block and place it on the green plate.",
      "s07 pick up the orange block and place it on the green plate.",
      "s08 pick up the yellow cup and place it on the green plate.",
      "s08 pick up the green block and place it on the green plate.",
      "s08 pick up the orange block and place it on the green plate.",
      "s08 pick up the gray cup and place it on the green plate.",
      "s08 pick up the light blue fork and place it on the green plate.",
      "s08 pick up the green knife and place it on the green plate.",
      "s09 pick up the green knife and place it on the green plate.",
      "s09 pick up the light blue fork and place it on the green plate.",
      "s09 pick up the orange block and place it on the green plate.",
      "s09 pick up the yellow spoon and place it on the green plate.",
      "s09 pick up the green block and place it on the green plate.",
      "s09 pick up the banana and place it on the green plate.",
      "s10 pick up the orange block and place it on the green plate.",
      "s10 pick up the green knife and place it on the green plate.",
      "s10 pick up the mango and place it on the green plate.",
      "s10 pick up the yellow spoon and place it on the green plate.",
      "s10 pick up the yellow cup and place it on the green plate.",
      "s10 pick up the banana and place it on the green plate.",
      "s11 pick up the star fruit and place it on the green plate.",
      "s11 pick up the gray cup and place it on the green plate.",
      "s11 pick up the mango and place it on the green plate.",
      "s11 pick up the orange block and place it on the green plate.",
      "s11 pick up the yellow cup and place it on the green plate.",
      "s11 pick up the green block and place it on the green plate.",
      "s12 pick up the yellow spoon and place it on the green plate.",
      "s12 pick up the light blue fork and place it on the green plate.",
      "s12 pick up the yellow cup and place it on the green plate.",
      "s12 pick up the star fruit and place it on the green plate.",
      "s12 pick up the green block and place it on the green plate.",
      "s12 pick up the gray cup and place it on the green plate.",
      "s13 pick up the gray cup and place it on the green plate.",
      "s13 pick up the star fruit and place it on the green plate.",
      "s13 pick up the yellow cup and place it on the green plate.",
      "s13 pick up the banana and place it on the green plate.",
      "s13 pick up the green knife and place it on the green plate.",
      "s13 pick up the green block and place it on the green plate.",
      "s14 pick up the orange block and place it on the green plate.",
      "s14 pick up the yellow cup and place it on the green plate.",
      "s14 pick up the banana and place it on the green plate.",
      "s14 pick up the mango and place it on the green plate.",
      "s14 pick up the green block and place it on the green plate.",
      "s14 pick up the gray cup and place it on the green plate.",
      "s15 pick up the mango and place it on the green plate.",
      "s15 pick up the orange block and place it on the green plate.",
      "s15 pick up the star fruit and place it on the green plate.",
      "s15 pick up the yellow spoon and place it on the green plate.",
      "s15 pick up the banana and place it on the green plate.",
      "s15 pick up the light blue fork and place it on the green plate."],
    # Number of successful trials to save for each task before EVA selects the
    # next task.  Adjust this number for the desired dataset balance.
    trials_per_task=5,
    )

    #   "pick up the banana and place it on the green plate.",
    #   "pick up the yellow spoon and place it on the green plate.",
    #   "pick up the star fruit and place it on the green plate.",
    #   "pick up the green knife and place it on the green plate.",
